#!/bin/sh
# SNIP=`pass snippets| dmenu -i -p 'Copy which url?' -l 10 | tr -d '\n'`
SNIP=`cat ~/.snippets| dmenu -i -p 'Inject which snippet?' -l 10 | tr -d '\n' | sed 's/.*://'`
echo $SNIP | tr -d '\n' | xclip -selection clipboard
xdotool key alt+v
