#!/bin/bash

# Gives a dmenu prompt to jump to a GCI Magento Ticket number.
# Without input, will open google.com.
# URLs will be directly handed to the browser.
# Anything else, it search it.
browser=${BROWSER:-google-chrome}

pgrep -x dmenu && exit

choice=$(echo "🎫" | dmenu -i -p "GCI Magento Ticket:") || exit 1

if [ "$choice" = "🎫"  ]; then
    $browser "https://github.com/giftcardimpressions/magento"
else
    # Detect if url
    if [[ "$choice" =~ ^(http:\/\/|https:\/\/)?[a-zA-Z0-9]+\.[a-zA-Z]+(/)?.*$ ]]; then
        $browser "$choice"
    else
        $browser "https://github.com/giftcardimpressions/magento/issues/$choice"
    fi
fi
