#!/bin/sh

i3lock -i /home/chadkouse/.config/wall.png -e -f -c 1d2021

# In five seconds, turn off display unless key press in last 4 seconds.
sleep 5 && [ 4000 -lt "$(xssstate -i)" ] &&  pgrep -x i3lock && xset dpms force off
