#!/bin/sh
# Sets the background. If given an argument, will set file as background.
/usr/bin/feh --randomize --bg-fill /usr/share/wallpapers/chromecast1200/*
selected=`sed '2q;d' ~/.fehbg | awk '{print $4}' | sed "s/'//g"`
echo $selected
wal -i $selected
