#!/bin/bash
# vlc -I dummy --no-video-deco --no-embedded-video rtsp://admin:cheddar526@10.0.1.44:554 &
# vlc -I dummy --no-video-deco --no-embedded-video rtsp://admin:cheddar526@10.0.1.31:554 &
# vlc -I dummy --no-video-deco --no-embedded-video rtsp://admin:cheddar526@10.0.1.40:554 &
# vlc -I dummy --no-video-deco --no-embedded-video rtsp://admin:cheddar526@10.0.1.54:554 &
# vlc -I dummy --no-video-deco --no-embedded-video rtsp://appagent:streaming@10.0.1.67:554 &
# vlc -I dummy --no-video-deco --no-embedded-video rtsp://appagent:streaming@10.0.1.68:554 &
#back door
vlc -I dummy --no-video-deco --no-embedded-video rtsp://admin:cheddar526@10.0.1.73:554/h264Preview_01_main &
#garage
vlc -I dummy --no-video-deco --no-embedded-video rtsp://admin:cheddar526@10.0.1.73:554/h264Preview_02_main &
#upper deck
vlc -I dummy --no-video-deco --no-embedded-video rtsp://admin:cheddar526@10.0.1.73:554/h264Preview_03_main &
#front door
vlc -I dummy --no-video-deco --no-embedded-video rtsp://admin:cheddar526@10.0.1.73:554/h264Preview_04_main &
#driveway
vlc -I dummy --no-video-deco --no-embedded-video rtsp://admin:cheddar526@10.0.1.73:554/h264Preview_05_main &
#side yard
vlc -I dummy --no-video-deco --no-embedded-video rtsp://admin:cheddar526@10.0.1.73:554/h264Preview_06_main &
#basement cam
vlc -I dummy --no-video-deco --no-embedded-video rtsp://admin:cheddar526@10.0.1.73:554/h264Preview_07_main &
#street cam
vlc -I dummy --no-video-deco --no-embedded-video rtsp://admin:cheddar526@10.0.1.73:554/h264Preview_08_main &

