#!/bin/bash
# amixer set 'Capture',0 toggle
mute_mic
pkill -RTMIN+17 dwmblocks

amixer get 'Capture',0 | grep -q '\[on\]'
MIC_OFF=$?

if [[ "$MIC_OFF" -eq 1 ]]; then
    notify-send "MIC OFF"
else
    notify-send "MIC ON"
fi
