#!/bin/bash
HOUR=`date "+%I"`
MINUTE=`date "+%M"`
DATE=`date '+%Y %b %d (%a) %I:%M:%S%p'`
if [ "$MINUTE" -gt 29 ]; then
  SUFFIX=$(($HOUR + 1371))
else
  SUFFIX=$(($HOUR + 1359))
fi
SUFFIX=`printf '%x\n' $SUFFIX`
ICON="\U0001F$SUFFIX"
CLOCK=`echo -e "$ICON"`
echo "$CLOCK $DATE"
