#!/bin/sh

case $BLOCK_BUTTON in
    3) $TERMINAL move_audio ;;
esac

# s=`mpc status | sed '/^volume:/d' | tr '\n' ' '`
player=`playerctl metadata | head -n 1 | awk '{print $1}'`
if [ "$player" == "vlc" ]
then
    echo " "
    exit
fi
banner=`playerctl metadata --format "{{ artist }} - {{ title }}"`
pstatus=`playerctl status`
pstatuslen=${#pstatus}
length=`expr 57 - $pstatuslen`
if [ "$pstatus" == "Playing" ] || [ "$pstatus" == "Stopped" ] || [ "$pstatus" == "No players found" ]
then
    pstatus=""
    length=60
else
    pstatus=" [$pstatus]"
fi

prefix=`echo "$banner" | awk -v l=$length '{print substr($0, 0, l)}'`
echo $prefix$pstatus
