#!/bin/sh

case $BLOCK_BUTTON in
	1) setsid "$TERMINAL" -e alsamixer & ;;
	2) amixer sset 'Master' toggle --quiet ;;
	4) amixer sset 'Master' 5%- --quiet ;;
	5) amixer sset 'Master' 5%+ --quiet ;;
	3) pgrep -x dunst >/dev/null && notify-send "<b>📢 Volume module:</b>
- Shows volume 🔊, 🔇 if muted.
- Middle click to mute.
- Scroll to change."
esac

[ "$(amixer sget Master | awk -F"[][]" '/dB/ { print $6 }')" = "off" ] && printf "🔇\\n" && exit

vol=$(amixer sget Master | awk -F"[][]" '/dB/ { print $2 }' | sed 's/\%//g')

if [ "$vol" -gt "70" ]; then
	icon="🔊"
elif [ "$vol" -lt "30" ]; then
	icon="🔈"
else
	icon="🔉"
fi

printf "%s %s%%\\n" "$icon" "$vol"
